server:
  port: 8081

spring:
  application:
    name: AGENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/AgentService
    username: postgres
    password: YANGao_2000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000