FROM openjdk:11-jre-slim
WORKDIR /app
COPY ./target/redbook-0.0.1-SNAPSHOT.jar /app/redbook.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx512m", "-Dspring.profiles.active=docker", "-jar", "/app/redbook.jar"]