spring.application.name=Spring-Security

server.port= 8088
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=123456
server.ssl.key-password=123456
server.ssl.key-alias=selfsigned
server.ssl.key-store-type=JKS