spring.application.name=httpsdemo
 spring.security.user.name=admin
 spring.security.user.password=admin123

# Run only on HTTPS (no HTTP connector)
server.port=8443

## SSL keystore settings (PKCS12)
#server.ssl.enabled=true
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-alias=httpsdemo



# SSL keystore settings (JKS)
server.ssl.enabled=true
server.ssl.key-store-type=JKS
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=changeit
server.ssl.key-alias=httpsdemo


# (Optional) tighten protocols/ciphers if needed
# server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
